version: "3.8"
services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5555:5555"
    volumes:
      - ./server:/app
    depends_on:
      - mongodb
    command: npm run start
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/ai-debate
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - JUDGE_ASSISTANT_ID=${JUDGE_ASSISTANT_ID}
      - DEBATE_CREATOR_ID=${DEBATE_CREATOR_ID}
      - DEBATE_MODEL=${DEBATE_MODEL}
      - SOLANA_PROGRAM_ID=${SOLANA_PROGRAM_ID}
      - SOLANA_JUNGLE_PDA=${SOLANA_JUNGLE_PDA}
      - SOLANA_DEVNET_RPC_URL=${SOLANA_DEVNET_RPC_URL}
      - SOLANA_MAINNET_RPC_URL=${SOLANA_MAINNET_RPC_URL}
      - TS_NODE_EXPERIMENTAL_SPECIFIER_RESOLUTION=node
      - TS_NODE_PROJECT=./tsconfig.json

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - WATCHPACK_POLLING=true
      - VITE_SOLANA_DEVNET_RPC_URL=${VITE_SOLANA_DEVNET_RPC_URL}
      - VITE_SOLANA_MAINNET_RPC_URL=${VITE_SOLANA_MAINNET_RPC_URL}
      - VITE_CA=${VITE_CA}
      - VITE_SOLANA_PROGRAM_ID=${VITE_SOLANA_PROGRAM_ID}
      - VITE_MODE=${VITE_MODE}
    depends_on:
      - server

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./web/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - client
      - server

volumes:
  mongodb_data:
